### 1. Sending requests | terminal
### 1.1 WITH security plugin
GET {{OPENSEARCH_HOST_HTTPS}}/_cluster/health
Authorization: Basic {{OPENSEARCH_AUTH}}

### 1.2. WITHOUT security plugin
GET {{OPENSEARCH_HOST}}/_cluster/health

### 2. pretty
GET {{OPENSEARCH_HOST}}/_cluster/health?pretty

### 3. request body
GET {{OPENSEARCH_HOST}}/students/_search?pretty
Content-Type: application/json

{
  "query": {
    "match_all": {}
  }
}

### 4. indexing documents
#   4.1                    /<index-name>/_doc/<document-id>
PUT {{OPENSEARCH_HOST}}/students/_doc/1
Content-Type: application/json

{
  "name": "John Doe",
  "gpa": 3.89,
  "grad_year": 2022
}

### 4.2 index documents WITHOUT providing documentId
POST {{OPENSEARCH_HOST}}/students/_doc
Content-Type: application/json

{
  "name": "Alfred Toledano",
  "gpa": 3.89,
  "grad_year": 2017
}